spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/glossElephant
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  type-handlers-package : com.exceedy.gen